apiVersion: v1
kind: ConfigMap
metadata:
  name: dob-config
  namespace: dob
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "dob"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  STORAGE_PROVIDER: "s3"
  AWS_REGION: "ap-south-1"
  S3_BUCKET: "dob-files"
  SERVER_PORT: "8080"
  CORS_ORIGINS: "https://dataofbusiness.in"
  LOG_LEVEL: "INFO"
